# Generated by Django 3.2.5 on 2021-07-20 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='активность')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='пометка удаленности')),
                ('text', models.CharField(blank=True, default='', help_text='Описание', max_length=1000, verbose_name='Текст вопроса')),
                ('answers_data', models.JSONField(default=list, verbose_name='Данные ответов')),
                ('additional_info', models.JSONField(blank=True, default=list, verbose_name='Дополнительные информация')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.poll', verbose_name='Опрос')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
